### ISSUE TITLE
html_quasiquotations not parsing valid HTML   method="POST" in forms not allowed

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/packages-http#1] opened 2015-02-14 20:38 UTC
``` prolog
:- use_module(library(http/html_write)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_parameters)).
:- use_module(library(http/http_session)).
:- use_module(library(http/html_quasiquotations)).


pay_with_card(Total) -->
    {
            setting(checkout:active_stripe_key, Key)
        },
    html( {|html(Total)||
<form action="/charge" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_2NwXWNYn4X732fdOEumVlz57"
    data-image="/square-image.png"
    data-name="Demo Site"
    data-description="2 widgets ($20.00)"
    data-amount="2000">
  </script>
</form>
         |}).
```

This example HTML is lifted straight from stripe.com's documentation.

On my machine 
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.1.29-5-g0a3d88a)

this won't compile, complaining about unexpected value, found `POST`
removing

``` prolog
 method="POST"
```

allows compilation

Adding structure around the HTML above passes the W3C's html5 validator

``` html
<!DOCTYPE html>
<html>
<head><title>foo</title></head>
<body>
 <form action="/charge" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_2NwXWNYn4X732fdOEumVlz57"
    data-image="/square-image.png"
    data-name="Demo Site"
    data-description="2 widgets ($20.00)"
    data-amount="2000">
  </script>
</form>

</body>
</html>
```

**Comment by wouterbeek** [comment] 2015-02-14 21:22
My first guess is that this is due to option `case_sensitive_attributes(true)` being set in `load_structure/3` as part of `load_html/3`. [In XML and XHTML the values of attributes should be in lowercase](http://www.w3.org/TR/xhtml1/diffs.html#h-4.11)

**Comment by wouterbeek** [comment] 2015-02-14 21:25
Indeed, removing this option from `html_quasiquotes` fixes the issue! I'm asking Jan whether this is indeed a bug or whether he had some deep insight as to why HTML should be forced to be XHTML.

**Comment by Anniepoo** [comment] 2015-02-14 21:31
While I understand case matters in attribute names, in this case the only uppercase is the _value_  "POST"  and it's uppercase in http 1.1 requests, which is why I made it that way.

**Comment by wouterbeek** [comment] 2015-02-14 21:34
The case-sensitivity difference between XML/XHTML and HTML 4 is indeed related to attribute _values_ (see the link in my previous comment). I've send the patch to Jan.

**Comment by Anniepoo** [comment] 2015-02-14 21:35
Ah, you are referring to 4.11. Attributes with pre-defined value sets
I was reading  4.2. Element and attribute names must be in lower case on same page

**Comment by Anniepoo** [comment] 2015-02-14 21:37
Now I'm wondering - is it a bug in the validator?

**Comment by wouterbeek** [comment] 2015-02-14 21:42
Ah, so we were on the same page after all :-) 

I believe that this indeed is a bug in the HTML quasiquoter. I've send a patch to Jan.

**Comment by Anniepoo** [comment] 2015-02-14 21:54
It does seem to be a bug in both the quasiquoter and the validator.  And a cool demo of the power of Prolog.

Related to 

https://bugzilla.validator.nu/show_bug.cgi?id=1019

**Comment by sideshowbarker** [comment] 2015-02-15 02:30
Hi. I'm one of the maintainers of the validator. Just chiming in here to echo what I said over at https://bugzilla.validator.nu/show_bug.cgi?id=1019 —which is that the validator is behaving as designed for this case, since it follows the requirements in the current HTML spec at http://www.w3.org/TR/html/ and not the requirements in the older XHTML1 spec.

**Comment by JanWielemaker** [comment] 2015-02-16 10:43
Should be fixed in the latest GIT version.  See SWI-Prolog/packages-http@
commit e20aef857fd0c3d83c2fe2838a4c8cc32a1c1676 and SWI-Prolog/packages-sgml@ece9e152912650b6e837d7197ecbb9c01000bbca.

**Closed as completed by JanWielemaker** 2015-02-16 10:43 UTC
Labels: bug
